name: Spring_boot_API_maven_java_applications

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: ['21']

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          overwrite-settings: true
          job-status: 'success'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Verify Java version
        run: java -version

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      # Step 2: Build the Spring Boot application
      - name: Build Spring Boot Application
        run: |
          cd java/spring_boot_rest_API_app_maven
          mvn clean package

      # Step 3: Run Spring Boot Application in the Background
      - name: Run Spring Boot App in Background
        run: |
          cd java/spring_boot_rest_API_app_maven
          java -jar target/*.jar &
          echo "Spring Boot app started in the background."
          sleep 5 # Give the app a few seconds to start

      # Step 5: Run Maven Tests
      - name: Run Maven Tests
        run: |
          cd java/spring_boot_rest_API_app_maven
          mvn test